name = "Treebars"
uuid = "e1e568c4-3a56-40a4-95fa-9b9c6c16fccb"
authors = ["Nikolas Siccha <nikolassiccha@gmail.com>"]
version = "0.1.0"

[deps]

[weakdeps]
HTMXObjects = "b12ef442-5798-4353-80f3-9562b03a0cb6"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
WarmupHMC = "60658175-6863-4866-a322-ab51a11c0cfe"

[extensions]
HTMXObjectsExt = "HTMXObjects"
TermExt = "Term"
WarmupHMCExt = "WarmupHMC"

[compat]
Term = "2"
julia = "1.10"
